version: "3.9"
services:
    backend:
        image: afilipovski/internship-backend
        container_name: backend
        ports:
            - "8080:8080"
        build:
            context: ../backend
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://finki-db:5432/finki-services-db
            - SPRING_DATASOURCE_USERNAME=finki_admin
            - SPRING_DATASOURCE_PASSWORD=f1nk1_@dm1n
            - SPRING_JPA_HIBERNATE_DDL_AUTO=update
        networks:
            - finki_services_net
    frontend:
        image: afilipovski/internship-frontend
        container_name: frontend
        ports:
            - "80:80"
        build:
            context: ../frontend
        environment:
            - BACKEND_BASE_URL=http://backend:8080/api
        networks:
            - finki_services_net
networks:
  finki_services_net:
      name: common-model_finki_services_net
      driver: bridge
      external: true